package com.autoapplyjobs.platform.user;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

import java.time.Instant;
import java.util.UUID;

/**
 * Maps to the {@code app_user} table exactly as defined in
 * {@code db/migration/V1__initial_schema.sql} (the source of truth) and
 * described in {@code docs/database-design.md}.
 *
 * <p>{@code id}, {@code created_at}, and {@code updated_at} are all
 * generated by PostgreSQL itself ({@code gen_random_uuid()}, {@code DEFAULT
 * now()}) - this entity never assigns them in Java. {@code id} uses
 * {@link GenerationType#IDENTITY} so Hibernate omits it from the INSERT and
 * reads the database-assigned value back via {@code RETURNING}, the same
 * pattern used for {@code created_at} / {@code updated_at} via
 * {@link Generated}. Nothing here duplicates a database default.
 *
 * <p>{@code updated_at} currently has no database trigger that refreshes it
 * on UPDATE - the migration only gives it an insert-time {@code DEFAULT
 * now()} - so it is mapped the same way as {@code created_at} (insert-only)
 * rather than assumed to be kept current by the database on every write.
 * Whether the application should start touching it on updates is a decision
 * for whenever update logic/services are introduced, not this mapping step.
 *
 * <p>{@code email}, {@code password_hash}, and {@code full_name} are all
 * {@code TEXT} in PostgreSQL (unbounded) - no {@code length} is set on
 * these columns because no such constraint exists in the database to
 * preserve.
 */
@Entity
@Table(name = "app_user")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /** CITEXT in PostgreSQL (case-insensitive) - mapped as a plain String. */
    @Column(name = "email", nullable = false, columnDefinition = "citext")
    private String email;

    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    @Column(name = "full_name", nullable = false)
    private String fullName;

    @Generated(event = EventType.INSERT)
    @Column(name = "created_at", nullable = false, insertable = false, updatable = false)
    private Instant createdAt;

    @Generated(event = EventType.INSERT)
    @Column(name = "updated_at", nullable = false, insertable = false, updatable = false)
    private Instant updatedAt;

    /** Required by JPA. */
    protected User() {
    }

    public User(String email, String passwordHash, String fullName) {
        this.email = email;
        this.passwordHash = passwordHash;
        this.fullName = fullName;
    }

    public UUID getId() {
        return id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof User other)) {
            return false;
        }
        return id != null && id.equals(other.id);
    }

    @Override
    public int hashCode() {
        // Stable across the entity lifecycle (id is null until persisted) -
        // see Vlad Mihalcea's "the best way to implement equals/hashCode
        // with JPA and Hibernate".
        return getClass().hashCode();
    }

    @Override
    public String toString() {
        // password_hash intentionally omitted.
        return "User{id=" + id + ", email=" + email + ", fullName=" + fullName + "}";
    }
}
